#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html
SERVER_CONFIG=\
	      "server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"




service nginx start
