#!/bin/bash
# Display listening sockets with PID and program name
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"


# Display listening TCP sockets
netstat -tuln | awk '$1 == "tcp" && $NF == "LISTEN" {print "tcp6       0      0 " $4 " " $6 "                  " $7 "      " $NF}' | while read line
do
    port=$(echo $line | awk '{print $5}' | cut -d: -f2)
    pid=$(lsof -i :$port -t)
    program=$(ps -p $pid -o comm=)
    echo "$line      $pid/$program"
done

# Display listening UDP sockets
netstat -uln | awk '$1 == "udp" && $NF == "0.0.0.0:*" {print "udp        0      0 " $4 "                                 " $NF}' | while read line
do
    port=$(echo $line | awk '{print $4}' | cut -d: -f2)
    pid=$(lsof -i :$port -t)
    program=$(ps -p $pid -o comm=)
    echo "$line      $pid/$program"
done

# Display active UNIX domain sockets
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

netstat -lx | awk '$1 == "unix" && $NF == "LISTEN" {print $0}' | while read line
do
    inode=$(echo $line | awk '{print $6}')
    pid=$(lsof -U -a -p 0 -d 0-99999 -F pni | awk -v inode="$inode" '$1 == "i" && $2 == inode {print $3}')
    program=$(ps -p $pid -o comm=)
    path=$(echo $line | awk '{print $NF}')
    echo "$line    $pid/$program    $path"
done